# Lab 2 — Pairwise Alignment, Homology Search and Multiple Sequence Alignment

## Exercise 1 — Implement Needleman–Wunsch and Smith–Waterman (Code)

**What you should do**

Implement two classic dynamic programming algorithms for sequence alignment:

* Needleman–Wunsch (NW) → global alignment
    * Aligns the entire sequence seq1 with the entire sequence seq2.
    * Best when sequences are expected to be similar across their full length.
* Smith–Waterman (SW) → local alignment
    * Finds the best matching subsequences inside seq1 and seq2.
    * Best when sequences may only share a conserved region (motif/domain).

### Needleman–Wunsch (Global Alignment)
#### Idea

NW tries to answer:

> “If I must align both sequences from start to end, what is the best alignment?”

It builds a dynamic programming matrix `S`, where `S[i, j]` stores the best possible score for aligning:

* `seq1[:i]` with `seq2[:j]`

#### Initialization matters

Because this is global alignment, gaps at the beginning count.
So the first row/column are filled with cumulative gap penalties.

Example intuition:

* Aligning first 3 chars of `seq1` with an empty sequence means 3 gaps → score = `3 * gap`

#### When to use NW

* Full-length homologous proteins
* Comparing similar genes/proteins end-to-end
* Cases where you care about the entire sequence, not just a motif

### Smith–Waterman (Local Alignment)
#### Idea

SW tries to answer:

> “What is the best matching region shared by these two sequences?”

Instead of forcing a full alignment, it finds the highest-scoring local region.
Each cell is computed as best of:
* diagonal, up, left and 0

Why 0?

If the alignment becomes bad (negative score), SW resets and starts a new local alignment region.
This is what makes it local.

In [3]:
# Needleman-Wunsch and Smith-Waterman implementations (reference)
import numpy as np
from typing import Tuple, List

def needleman_wunsch(seq1: str, seq2: str, match: int=1, mismatch: int=-1, gap: int=-2) -> Tuple[str, str, np.ndarray]:
    n, m = len(seq1), len(seq2)
    score_matrix = np.zeros((n+1, m+1), dtype=float)

    aligned1 = ''
    aligned2 = ''
    return aligned1, aligned2, score_matrix
    

def smith_waterman(seq1: str, seq2: str, match: int=2, mismatch: int=-1, gap: int=-2) -> Tuple[str, str, np.ndarray, float]:
    # uses 0 floor
    n, m = len(seq1), len(seq2)
    score_matrix = np.zeros((n+1, m+1), dtype=float)
    max_i = max_j = 0
    max_score = 0.0
    aligned1 = ''
    aligned2 = ''

    return aligned1, aligned2, score_matrix, max_score
    
# Demo run
seqA = "GATTACA"
seqB = "GCATGCU"

alnA, alnB, S_nw = needleman_wunsch(seqA, seqB, match=1, mismatch=-1, gap=-2)
print("Needleman-Wunsch alignment:")
print(alnA)
print(alnB)
print("\nSmith-Waterman (local):")
alnA2, alnB2, S_sw, max_score = smith_waterman(seqA, seqB, match=2, mismatch=-1, gap=-2)
print(alnA2)
print(alnB2)
print("\nNW score matrix (snippet):")
print(S_nw)

Needleman-Wunsch alignment:



Smith-Waterman (local):



NW score matrix (snippet):
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


## Exercise 2 — Biotite pairwise alignment (Protein & Nucleotide examples)

**Goal:** Demonstrate pairwise API for local/global alignment using substitution matrices.

In [21]:
import matplotlib.pyplot as plt
import biotite.database.entrez as entrez
import biotite.sequence as seq
import biotite.sequence.align as align
import biotite.sequence.graphics as graphics
import biotite.sequence.io.fasta as fasta

# Protein example (small Ras sequence fragment)
prot1 = seq.ProteinSequence("MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQV")
prot2 = seq.ProteinSequence("MTEYKLVVVGAGGVGKSALTIKLIGRNHFVDEYDPTIEDSYRKQV")  # small change

# TODO load proper matrix using align.SubstitutionMatrix
# align protein sequences usign align optimal with -10, -1 penalty gaps. 
# Check different gap peanlties and terminal penalty
# Create a visualization with graphics.plot_alignment_similarity_based

matrix = 
alignments = 
fig =

SyntaxError: invalid syntax (597466206.py, line 17)

In [20]:
# # Nucleotide example
seq1 = seq.NucleotideSequence("ATGCGTACGTTAG")
seq2 = seq.NucleotideSequence("ATGTACGTAG")

# TODO load proper matrix using align.SubstitutionMatrix
# align nucleotide sequences usign align optimal with -2, -1 penalty gaps. 
# Check different gap peanlties and terminal penalty
# Create a visualization with graphics.plot_alignment_similarity_based

matrix = 
alignments = 
fig = 

SyntaxError: invalid syntax (925465965.py, line 10)

## Exercise 3 — BLAST via NCBIWWW (Protein and Nucleotide)

**Goal:** Submit BLASTp and BLASTn jobs programmatically and parse results. Plot E-value vs Bit score, Identity vs Query Coverage and Bit Score vs Identity. Warning: These cells will make live network calls to NCBI. If running in a restricted environment, comment out the network cells and use the provided offline fallback below.


Unfortunately, Biotite works really bad with BLAST app (but it's still possible!).
Personally, I recommend using Biopython for that.

In [23]:
# Protein BLAST (BLASTp) example - [NETWORK REQUIRED]
from Bio.Blast import NCBIWWW, NCBIXML
prot_query = 'MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQV'  # RAS fragment

# TODO use NCBIWWW.qblast() to submit BLASTp query, use NCBIXML.read() to parse results
# Print top 5 hits, plot E-value vs Bit score, Identity vs Query Coverage and Bit Score vs Identity
# Plot E-value vs Bit score
# Plot Identity vs Query Coverage
# Plot Bit Score vs Identity

In [24]:
# TODO perform BLASTn search for the query. Print top5 results. Print E-value and bit score for each hit.
# Nucleotide BLAST (BLASTn) example - [NETWORK REQUIRED]
from Bio.Blast import NCBIWWW, NCBIXML
nt_query = 'ATGCGTACGTTAGCTAGCTAGCTAGCTAG'  # synthetic

## Exercise 4 — Sequence Embeddings (Protein & Nucleotide)
**Goal:** Provide an example of using pretrained models to compute embeddings and compare similarity without alignment.
- Protein models: ESM, ProtTrans (HuggingFace)  


In [25]:
# Example with HuggingFace transformers (protein model) - [NETWORK REQUIRED]
# First install: pip install transformers sentencepiece torch

try:s
    from transformers import AutoTokenizer, AutoModel
    import torch
    import numpy as np
    from sklearn.metrics.pairwise import cosine_similarity
    
    print("Loading ESM2 model from HuggingFace...")
    tokenizer = AutoTokenizer.from_pretrained("facebook/esm2_t6_8M_UR50D")
    model = AutoModel.from_pretrained("facebook/esm2_t6_8M_UR50D")
    
    # Two protein sequences to compare
    seq1 = "MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQV"
    seq2 = "MTEYKLVVVGAGGVGKSALTIKLIGRNHFVDEYDPTIEDSYRKQV"  # Same sequence for demo
    
    print(f"Sequence 1: {seq1}")
    print(f"Sequence 2: {seq2}")
    
    # TODO Tokenize inputs using ESM2 tokenizer
    # TODO Get embeddings using ESM2 model
    # TODO Calculate cosine similarity between embeddings
    # TODO Print similarity score

SyntaxError: incomplete input (3352073549.py, line 24)